"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kombo.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from kombo.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, NotRequired, TypedDict


GetAssessmentOrdersPositiveResponseStatus = Literal[
    "OPEN",
    "COMPLETED",
    "CANCELLED",
    "REJECTED",
]
r"""The current status of the assessment order."""


class GetAssessmentOrdersPositiveResponseCandidateTypedDict(TypedDict):
    r"""Information about the candidate taking the assessment."""

    remote_id: Nullable[str]
    r"""The candidate's identifier in the integrated system."""
    email: str
    r"""The candidate's email address."""
    first_name: Nullable[str]
    r"""The candidate's first name."""
    last_name: Nullable[str]
    r"""The candidate's last name."""
    phone: Nullable[str]
    r"""The candidate's phone number."""


class GetAssessmentOrdersPositiveResponseCandidate(BaseModel):
    r"""Information about the candidate taking the assessment."""

    remote_id: Nullable[str]
    r"""The candidate's identifier in the integrated system."""

    email: str
    r"""The candidate's email address."""

    first_name: Nullable[str]
    r"""The candidate's first name."""

    last_name: Nullable[str]
    r"""The candidate's last name."""

    phone: Nullable[str]
    r"""The candidate's phone number."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetAssessmentOrdersPositiveResponseApplicationTypedDict(TypedDict):
    r"""Information about the job application."""

    remote_id: Nullable[str]
    r"""The application's identifier in the integrated system."""


class GetAssessmentOrdersPositiveResponseApplication(BaseModel):
    r"""Information about the job application."""

    remote_id: Nullable[str]
    r"""The application's identifier in the integrated system."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetAssessmentOrdersPositiveResponseLocationTypedDict(TypedDict):
    r"""The job location information."""

    street_1: NotRequired[Nullable[str]]
    r"""If we can parse the address data, this field contains the first part of the street information."""
    street_2: NotRequired[Nullable[str]]
    city: NotRequired[Nullable[str]]
    state: NotRequired[Nullable[str]]
    zip_code: NotRequired[Nullable[str]]
    country: NotRequired[Nullable[str]]
    r"""Contains the ISO2 country code if possible. If not, it contains the original value."""
    raw: NotRequired[Nullable[str]]
    r"""If we have address data, this is filled with the raw address string."""


class GetAssessmentOrdersPositiveResponseLocation(BaseModel):
    r"""The job location information."""

    street_1: OptionalNullable[str] = UNSET
    r"""If we can parse the address data, this field contains the first part of the street information."""

    street_2: OptionalNullable[str] = UNSET

    city: OptionalNullable[str] = UNSET

    state: OptionalNullable[str] = UNSET

    zip_code: OptionalNullable[str] = UNSET

    country: OptionalNullable[str] = UNSET
    r"""Contains the ISO2 country code if possible. If not, it contains the original value."""

    raw: OptionalNullable[str] = UNSET
    r"""If we have address data, this is filled with the raw address string."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["street_1", "street_2", "city", "state", "zip_code", "country", "raw"]
        )
        nullable_fields = set(
            ["street_1", "street_2", "city", "state", "zip_code", "country", "raw"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


GetAssessmentOrdersPositiveResponseHiringTeamRole = Literal[
    "RECRUITER",
    "HIRING_MANAGER",
    "COORDINATOR",
    "SOURCER",
    "INTERVIEWER",
]


class GetAssessmentOrdersPositiveResponseHiringTeamTypedDict(TypedDict):
    r"""A member of the hiring team."""

    remote_id: Nullable[str]
    r"""The team member's identifier in the integrated system."""
    email: Nullable[str]
    r"""The team member's email address."""
    first_name: Nullable[str]
    r"""The team member's first name."""
    last_name: Nullable[str]
    r"""The team member's last name."""
    hiring_team_roles: List[GetAssessmentOrdersPositiveResponseHiringTeamRole]
    r"""Array of the roles of the user for this specific job. Currently only `RECRUITER` and `HIRING_MANAGER` are mapped into our unified schema."""


class GetAssessmentOrdersPositiveResponseHiringTeam(BaseModel):
    r"""A member of the hiring team."""

    remote_id: Nullable[str]
    r"""The team member's identifier in the integrated system."""

    email: Nullable[str]
    r"""The team member's email address."""

    first_name: Nullable[str]
    r"""The team member's first name."""

    last_name: Nullable[str]
    r"""The team member's last name."""

    hiring_team_roles: List[GetAssessmentOrdersPositiveResponseHiringTeamRole]
    r"""Array of the roles of the user for this specific job. Currently only `RECRUITER` and `HIRING_MANAGER` are mapped into our unified schema."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetAssessmentOrdersPositiveResponseJobTypedDict(TypedDict):
    r"""Information about the job posting."""

    remote_id: Nullable[str]
    r"""The job's identifier in the integrated system."""
    name: Nullable[str]
    r"""The job title."""
    job_code: Nullable[str]
    r"""The human readable job code. Some systems expose this as the Requisition Code/ID."""
    description: Nullable[str]
    r"""Description of the job. This field is usually returned as HTML."""
    location: Nullable[GetAssessmentOrdersPositiveResponseLocationTypedDict]
    r"""The job location information."""
    hiring_team: List[GetAssessmentOrdersPositiveResponseHiringTeamTypedDict]
    r"""The hiring team allows you to provision users into your system who can access the job and its applications."""


class GetAssessmentOrdersPositiveResponseJob(BaseModel):
    r"""Information about the job posting."""

    remote_id: Nullable[str]
    r"""The job's identifier in the integrated system."""

    name: Nullable[str]
    r"""The job title."""

    job_code: Nullable[str]
    r"""The human readable job code. Some systems expose this as the Requisition Code/ID."""

    description: Nullable[str]
    r"""Description of the job. This field is usually returned as HTML."""

    location: Nullable[GetAssessmentOrdersPositiveResponseLocation]
    r"""The job location information."""

    hiring_team: List[GetAssessmentOrdersPositiveResponseHiringTeam]
    r"""The hiring team allows you to provision users into your system who can access the job and its applications."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetAssessmentOrdersPositiveResponseResultTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the assessment order."""
    package_id: str
    r"""The identifier of the assessment package."""
    status: GetAssessmentOrdersPositiveResponseStatus
    r"""The current status of the assessment order."""
    candidate: GetAssessmentOrdersPositiveResponseCandidateTypedDict
    r"""Information about the candidate taking the assessment."""
    application: GetAssessmentOrdersPositiveResponseApplicationTypedDict
    r"""Information about the job application."""
    job: GetAssessmentOrdersPositiveResponseJobTypedDict
    r"""Information about the job posting."""


class GetAssessmentOrdersPositiveResponseResult(BaseModel):
    id: str
    r"""The unique identifier of the assessment order."""

    package_id: str
    r"""The identifier of the assessment package."""

    status: GetAssessmentOrdersPositiveResponseStatus
    r"""The current status of the assessment order."""

    candidate: GetAssessmentOrdersPositiveResponseCandidate
    r"""Information about the candidate taking the assessment."""

    application: GetAssessmentOrdersPositiveResponseApplication
    r"""Information about the job application."""

    job: GetAssessmentOrdersPositiveResponseJob
    r"""Information about the job posting."""


class GetAssessmentOrdersPositiveResponseDataTypedDict(TypedDict):
    next: Nullable[str]
    results: List[GetAssessmentOrdersPositiveResponseResultTypedDict]


class GetAssessmentOrdersPositiveResponseData(BaseModel):
    next: Nullable[str]

    results: List[GetAssessmentOrdersPositiveResponseResult]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetAssessmentOrdersPositiveResponseTypedDict(TypedDict):
    data: GetAssessmentOrdersPositiveResponseDataTypedDict
    status: Literal["success"]


class GetAssessmentOrdersPositiveResponse(BaseModel):
    data: GetAssessmentOrdersPositiveResponseData

    STATUS: Annotated[
        Annotated[Literal["success"], AfterValidator(validate_const("success"))],
        pydantic.Field(alias="status"),
    ] = "success"


try:
    GetAssessmentOrdersPositiveResponse.model_rebuild()
except NameError:
    pass
