"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from kombo.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from kombo.utils import validate_const
import pydantic
from pydantic import Field, model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class ResultDateTypedDict(TypedDict):
    remote_id: Nullable[str]
    r"""ID of the question in the connected ATS. `null` when the ATS keeps the headline rating or summary outside the rubric."""
    label: str
    r"""The question or attribute being assessed, e.g. \"Willingness to travel\"."""
    description: Nullable[str]
    r"""Guidance the ATS shows the interviewer below the question, e.g. \"1 is poor, 4 is great\"."""
    required: Nullable[bool]
    r"""Whether the ATS marked this question mandatory."""
    answer: Nullable[str]
    r"""Date in `YYYY-MM-DD` format."""
    type: Literal["DATE"]


class ResultDate(BaseModel):
    remote_id: Nullable[str]
    r"""ID of the question in the connected ATS. `null` when the ATS keeps the headline rating or summary outside the rubric."""

    label: str
    r"""The question or attribute being assessed, e.g. \"Willingness to travel\"."""

    description: Nullable[str]
    r"""Guidance the ATS shows the interviewer below the question, e.g. \"1 is poor, 4 is great\"."""

    required: Nullable[bool]
    r"""Whether the ATS marked this question mandatory."""

    answer: Nullable[str]
    r"""Date in `YYYY-MM-DD` format."""

    TYPE: Annotated[
        Annotated[Literal["DATE"], AfterValidator(validate_const("DATE"))],
        pydantic.Field(alias="type"),
    ] = "DATE"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class ResultNumberTypedDict(TypedDict):
    remote_id: Nullable[str]
    r"""ID of the question in the connected ATS. `null` when the ATS keeps the headline rating or summary outside the rubric."""
    label: str
    r"""The question or attribute being assessed, e.g. \"Willingness to travel\"."""
    description: Nullable[str]
    r"""Guidance the ATS shows the interviewer below the question, e.g. \"1 is poor, 4 is great\"."""
    required: Nullable[bool]
    r"""Whether the ATS marked this question mandatory."""
    answer: Nullable[float]
    r"""A decimal value."""
    type: Literal["NUMBER"]


class ResultNumber(BaseModel):
    remote_id: Nullable[str]
    r"""ID of the question in the connected ATS. `null` when the ATS keeps the headline rating or summary outside the rubric."""

    label: str
    r"""The question or attribute being assessed, e.g. \"Willingness to travel\"."""

    description: Nullable[str]
    r"""Guidance the ATS shows the interviewer below the question, e.g. \"1 is poor, 4 is great\"."""

    required: Nullable[bool]
    r"""Whether the ATS marked this question mandatory."""

    answer: Nullable[float]
    r"""A decimal value."""

    TYPE: Annotated[
        Annotated[Literal["NUMBER"], AfterValidator(validate_const("NUMBER"))],
        pydantic.Field(alias="type"),
    ] = "NUMBER"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class ResultBooleanTypedDict(TypedDict):
    remote_id: Nullable[str]
    r"""ID of the question in the connected ATS. `null` when the ATS keeps the headline rating or summary outside the rubric."""
    label: str
    r"""The question or attribute being assessed, e.g. \"Willingness to travel\"."""
    description: Nullable[str]
    r"""Guidance the ATS shows the interviewer below the question, e.g. \"1 is poor, 4 is great\"."""
    required: Nullable[bool]
    r"""Whether the ATS marked this question mandatory."""
    answer: Nullable[bool]
    r"""The yes/no the interviewer picked."""
    type: Literal["BOOLEAN"]


class ResultBoolean(BaseModel):
    remote_id: Nullable[str]
    r"""ID of the question in the connected ATS. `null` when the ATS keeps the headline rating or summary outside the rubric."""

    label: str
    r"""The question or attribute being assessed, e.g. \"Willingness to travel\"."""

    description: Nullable[str]
    r"""Guidance the ATS shows the interviewer below the question, e.g. \"1 is poor, 4 is great\"."""

    required: Nullable[bool]
    r"""Whether the ATS marked this question mandatory."""

    answer: Nullable[bool]
    r"""The yes/no the interviewer picked."""

    TYPE: Annotated[
        Annotated[Literal["BOOLEAN"], AfterValidator(validate_const("BOOLEAN"))],
        pydantic.Field(alias="type"),
    ] = "BOOLEAN"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetAtsScorecardsPositiveResponseOption2TypedDict(TypedDict):
    remote_id: Nullable[str]
    r"""The ID of this option in the remote system, e.g. `strong_hire`. `null` when the system identifies the option only by its label."""
    label: str
    r"""The option as the interviewer sees it, e.g. \"Strong Hire\"."""


class GetAtsScorecardsPositiveResponseOption2(BaseModel):
    remote_id: Nullable[str]
    r"""The ID of this option in the remote system, e.g. `strong_hire`. `null` when the system identifies the option only by its label."""

    label: str
    r"""The option as the interviewer sees it, e.g. \"Strong Hire\"."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetAtsScorecardsPositiveResponseAnswer2TypedDict(TypedDict):
    remote_id: Nullable[str]
    r"""The ID of this option in the remote system, e.g. `strong_hire`. `null` when the system identifies the option only by its label."""
    label: str
    r"""The option as the interviewer sees it, e.g. \"Strong Hire\"."""


class GetAtsScorecardsPositiveResponseAnswer2(BaseModel):
    remote_id: Nullable[str]
    r"""The ID of this option in the remote system, e.g. `strong_hire`. `null` when the system identifies the option only by its label."""

    label: str
    r"""The option as the interviewer sees it, e.g. \"Strong Hire\"."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class ResultMultiSelectTypedDict(TypedDict):
    remote_id: Nullable[str]
    r"""ID of the question in the connected ATS. `null` when the ATS keeps the headline rating or summary outside the rubric."""
    label: str
    r"""The question or attribute being assessed, e.g. \"Willingness to travel\"."""
    description: Nullable[str]
    r"""Guidance the ATS shows the interviewer below the question, e.g. \"1 is poor, 4 is great\"."""
    required: Nullable[bool]
    r"""Whether the ATS marked this question mandatory."""
    options: List[GetAtsScorecardsPositiveResponseOption2TypedDict]
    r"""Every option available for select and multi-select questions."""
    answer: Nullable[List[GetAtsScorecardsPositiveResponseAnswer2TypedDict]]
    r"""An array of ids and labels with every selected option."""
    type: Literal["MULTI_SELECT"]


class ResultMultiSelect(BaseModel):
    remote_id: Nullable[str]
    r"""ID of the question in the connected ATS. `null` when the ATS keeps the headline rating or summary outside the rubric."""

    label: str
    r"""The question or attribute being assessed, e.g. \"Willingness to travel\"."""

    description: Nullable[str]
    r"""Guidance the ATS shows the interviewer below the question, e.g. \"1 is poor, 4 is great\"."""

    required: Nullable[bool]
    r"""Whether the ATS marked this question mandatory."""

    options: List[GetAtsScorecardsPositiveResponseOption2]
    r"""Every option available for select and multi-select questions."""

    answer: Nullable[List[GetAtsScorecardsPositiveResponseAnswer2]]
    r"""An array of ids and labels with every selected option."""

    TYPE: Annotated[
        Annotated[
            Literal["MULTI_SELECT"], AfterValidator(validate_const("MULTI_SELECT"))
        ],
        pydantic.Field(alias="type"),
    ] = "MULTI_SELECT"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetAtsScorecardsPositiveResponseOption1TypedDict(TypedDict):
    remote_id: Nullable[str]
    r"""The ID of this option in the remote system, e.g. `strong_hire`. `null` when the system identifies the option only by its label."""
    label: str
    r"""The option as the interviewer sees it, e.g. \"Strong Hire\"."""


class GetAtsScorecardsPositiveResponseOption1(BaseModel):
    remote_id: Nullable[str]
    r"""The ID of this option in the remote system, e.g. `strong_hire`. `null` when the system identifies the option only by its label."""

    label: str
    r"""The option as the interviewer sees it, e.g. \"Strong Hire\"."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetAtsScorecardsPositiveResponseAnswer1TypedDict(TypedDict):
    r"""The id and label of the selected option."""

    remote_id: Nullable[str]
    r"""The ID of this option in the remote system, e.g. `strong_hire`. `null` when the system identifies the option only by its label."""
    label: str
    r"""The option as the interviewer sees it, e.g. \"Strong Hire\"."""


class GetAtsScorecardsPositiveResponseAnswer1(BaseModel):
    r"""The id and label of the selected option."""

    remote_id: Nullable[str]
    r"""The ID of this option in the remote system, e.g. `strong_hire`. `null` when the system identifies the option only by its label."""

    label: str
    r"""The option as the interviewer sees it, e.g. \"Strong Hire\"."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class ResultSingleSelectTypedDict(TypedDict):
    remote_id: Nullable[str]
    r"""ID of the question in the connected ATS. `null` when the ATS keeps the headline rating or summary outside the rubric."""
    label: str
    r"""The question or attribute being assessed, e.g. \"Willingness to travel\"."""
    description: Nullable[str]
    r"""Guidance the ATS shows the interviewer below the question, e.g. \"1 is poor, 4 is great\"."""
    required: Nullable[bool]
    r"""Whether the ATS marked this question mandatory."""
    options: List[GetAtsScorecardsPositiveResponseOption1TypedDict]
    r"""Every option available for select and multi-select questions."""
    answer: Nullable[GetAtsScorecardsPositiveResponseAnswer1TypedDict]
    r"""The id and label of the selected option."""
    type: Literal["SINGLE_SELECT"]


class ResultSingleSelect(BaseModel):
    remote_id: Nullable[str]
    r"""ID of the question in the connected ATS. `null` when the ATS keeps the headline rating or summary outside the rubric."""

    label: str
    r"""The question or attribute being assessed, e.g. \"Willingness to travel\"."""

    description: Nullable[str]
    r"""Guidance the ATS shows the interviewer below the question, e.g. \"1 is poor, 4 is great\"."""

    required: Nullable[bool]
    r"""Whether the ATS marked this question mandatory."""

    options: List[GetAtsScorecardsPositiveResponseOption1]
    r"""Every option available for select and multi-select questions."""

    answer: Nullable[GetAtsScorecardsPositiveResponseAnswer1]
    r"""The id and label of the selected option."""

    TYPE: Annotated[
        Annotated[
            Literal["SINGLE_SELECT"], AfterValidator(validate_const("SINGLE_SELECT"))
        ],
        pydantic.Field(alias="type"),
    ] = "SINGLE_SELECT"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class ResultTextTypedDict(TypedDict):
    remote_id: Nullable[str]
    r"""ID of the question in the connected ATS. `null` when the ATS keeps the headline rating or summary outside the rubric."""
    label: str
    r"""The question or attribute being assessed, e.g. \"Willingness to travel\"."""
    description: Nullable[str]
    r"""Guidance the ATS shows the interviewer below the question, e.g. \"1 is poor, 4 is great\"."""
    required: Nullable[bool]
    r"""Whether the ATS marked this question mandatory."""
    answer: Nullable[str]
    r"""The text the interviewer wrote."""
    type: Literal["TEXT"]


class ResultText(BaseModel):
    remote_id: Nullable[str]
    r"""ID of the question in the connected ATS. `null` when the ATS keeps the headline rating or summary outside the rubric."""

    label: str
    r"""The question or attribute being assessed, e.g. \"Willingness to travel\"."""

    description: Nullable[str]
    r"""Guidance the ATS shows the interviewer below the question, e.g. \"1 is poor, 4 is great\"."""

    required: Nullable[bool]
    r"""Whether the ATS marked this question mandatory."""

    answer: Nullable[str]
    r"""The text the interviewer wrote."""

    TYPE: Annotated[
        Annotated[Literal["TEXT"], AfterValidator(validate_const("TEXT"))],
        pydantic.Field(alias="type"),
    ] = "TEXT"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


ResponseTypedDict = TypeAliasType(
    "ResponseTypedDict",
    Union[
        ResultTextTypedDict,
        ResultBooleanTypedDict,
        ResultNumberTypedDict,
        ResultDateTypedDict,
        ResultSingleSelectTypedDict,
        ResultMultiSelectTypedDict,
    ],
)


Response = Annotated[
    Union[
        ResultText,
        ResultSingleSelect,
        ResultMultiSelect,
        ResultBoolean,
        ResultNumber,
        ResultDate,
    ],
    Field(discriminator="TYPE"),
]


class GetAtsScorecardsPositiveResponseAuthorTypedDict(TypedDict):
    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""
    remote_id: Nullable[str]
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""
    first_name: Nullable[str]
    r"""First name of the user."""
    last_name: Nullable[str]
    r"""Last name of the user."""
    email: NotRequired[Nullable[str]]
    r"""Email of the user. If the email address is invalid, it will be set to null."""


class GetAtsScorecardsPositiveResponseAuthor(BaseModel):
    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""

    remote_id: Nullable[str]
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""

    first_name: Nullable[str]
    r"""First name of the user."""

    last_name: Nullable[str]
    r"""Last name of the user."""

    email: OptionalNullable[str] = UNSET
    r"""Email of the user. If the email address is invalid, it will be set to null."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["email"])
        nullable_fields = set(["remote_id", "first_name", "last_name", "email"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetAtsScorecardsPositiveResponseResultTypedDict(TypedDict):
    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""
    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""
    candidate_id: Nullable[str]
    r"""The Kombo ID of the candidate this scorecard evaluates."""
    application_id: Nullable[str]
    r"""The Kombo ID of the application this scorecard belongs to."""
    interview_id: Nullable[str]
    r"""The Kombo ID of the interview this scorecard was submitted against."""
    author_id: Nullable[str]
    r"""The Kombo ID of the user this evaluation belongs to. Where the ATS distinguishes who submitted the scorecard from whose review it is, this is the source of the opinion (the user whose evaluation it is, not whoever entered it). The ID can be used to retrieve the user from the `get users` endpoint."""
    remote_created_at: Nullable[datetime]
    r"""The date and time the object was created in the remote system.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    remote_updated_at: Nullable[datetime]
    r"""A timestamp retrieved from the remote system, describing when the resource was last updated.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    changed_at: datetime
    r"""The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    remote_deleted_at: Nullable[datetime]
    r"""The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    author: Nullable[GetAtsScorecardsPositiveResponseAuthorTypedDict]
    responses: NotRequired[Nullable[List[ResponseTypedDict]]]
    r"""Every question on the scorecard, together with its definition and the answer submitted by the interviewer."""


class GetAtsScorecardsPositiveResponseResult(BaseModel):
    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""

    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""

    candidate_id: Nullable[str]
    r"""The Kombo ID of the candidate this scorecard evaluates."""

    application_id: Nullable[str]
    r"""The Kombo ID of the application this scorecard belongs to."""

    interview_id: Nullable[str]
    r"""The Kombo ID of the interview this scorecard was submitted against."""

    author_id: Nullable[str]
    r"""The Kombo ID of the user this evaluation belongs to. Where the ATS distinguishes who submitted the scorecard from whose review it is, this is the source of the opinion (the user whose evaluation it is, not whoever entered it). The ID can be used to retrieve the user from the `get users` endpoint."""

    remote_created_at: Nullable[datetime]
    r"""The date and time the object was created in the remote system.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """

    remote_updated_at: Nullable[datetime]
    r"""A timestamp retrieved from the remote system, describing when the resource was last updated.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """

    changed_at: datetime
    r"""The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """

    remote_deleted_at: Nullable[datetime]
    r"""The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """

    author: Nullable[GetAtsScorecardsPositiveResponseAuthor]

    responses: OptionalNullable[List[Response]] = UNSET
    r"""Every question on the scorecard, together with its definition and the answer submitted by the interviewer."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["responses"])
        nullable_fields = set(
            [
                "candidate_id",
                "application_id",
                "interview_id",
                "author_id",
                "responses",
                "remote_created_at",
                "remote_updated_at",
                "remote_deleted_at",
                "author",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetAtsScorecardsPositiveResponseDataTypedDict(TypedDict):
    next: Nullable[str]
    r"""Cursor string that can be passed to the `cursor` query parameter to get the next page. If this is `null`, then there are no more pages."""
    results: List[GetAtsScorecardsPositiveResponseResultTypedDict]


class GetAtsScorecardsPositiveResponseData(BaseModel):
    next: Nullable[str]
    r"""Cursor string that can be passed to the `cursor` query parameter to get the next page. If this is `null`, then there are no more pages."""

    results: List[GetAtsScorecardsPositiveResponseResult]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetAtsScorecardsPositiveResponseTypedDict(TypedDict):
    data: GetAtsScorecardsPositiveResponseDataTypedDict
    status: Literal["success"]


class GetAtsScorecardsPositiveResponse(BaseModel):
    data: GetAtsScorecardsPositiveResponseData

    STATUS: Annotated[
        Annotated[Literal["success"], AfterValidator(validate_const("success"))],
        pydantic.Field(alias="status"),
    ] = "success"


try:
    ResultDate.model_rebuild()
except NameError:
    pass
try:
    ResultNumber.model_rebuild()
except NameError:
    pass
try:
    ResultBoolean.model_rebuild()
except NameError:
    pass
try:
    ResultMultiSelect.model_rebuild()
except NameError:
    pass
try:
    ResultSingleSelect.model_rebuild()
except NameError:
    pass
try:
    ResultText.model_rebuild()
except NameError:
    pass
try:
    GetAtsScorecardsPositiveResponse.model_rebuild()
except NameError:
    pass
