"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from kombo.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from kombo.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, NotRequired, TypedDict


GetAtsAttachmentsPositiveResponseType = Literal[
    "CV",
    "COVER_LETTER",
    "OTHER",
]
r"""What the file is used for in the ATS. Anything that is neither a CV nor a cover letter is reported as `OTHER`."""


class ContentRefTypedDict(TypedDict):
    bucket: str
    r"""The bucket the object was written to."""
    key: str
    r"""The full object key, including the prefix configured on the file destination."""
    type: Literal["s3"]


class ContentRef(BaseModel):
    bucket: str
    r"""The bucket the object was written to."""

    key: str
    r"""The full object key, including the prefix configured on the file destination."""

    TYPE: Annotated[
        Annotated[Literal["s3"], AfterValidator(validate_const("s3"))],
        pydantic.Field(alias="type"),
    ] = "s3"


class GetAtsAttachmentsPositiveResponseResultTypedDict(TypedDict):
    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""
    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""
    candidate_id: str
    r"""The Kombo ID of the candidate this attachment belongs to. The ID can be used to retrieve the candidate from the `get candidates` endpoint."""
    application_id: Nullable[str]
    r"""The Kombo ID of the application this attachment belongs to, when the ATS files it under one specific application. Many systems attach files to the candidate instead, in which case this is `null`."""
    type: Nullable[GetAtsAttachmentsPositiveResponseType]
    r"""What the file is used for in the ATS. Anything that is neither a CV nor a cover letter is reported as `OTHER`."""
    file_name: Nullable[str]
    r"""The name of the file as reported by the ATS."""
    remote_created_at: Nullable[datetime]
    r"""The date and time the object was created in the remote system.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    remote_updated_at: Nullable[datetime]
    r"""A timestamp retrieved from the remote system, describing when the resource was last updated.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    changed_at: datetime
    r"""The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    remote_deleted_at: Nullable[datetime]
    r"""The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    content_ref: NotRequired[Nullable[ContentRefTypedDict]]
    r"""Where we stored the file in the bucket you configured. The file is written before the attachment shows up here, so this is set on every attachment you can read."""


class GetAtsAttachmentsPositiveResponseResult(BaseModel):
    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""

    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""

    candidate_id: str
    r"""The Kombo ID of the candidate this attachment belongs to. The ID can be used to retrieve the candidate from the `get candidates` endpoint."""

    application_id: Nullable[str]
    r"""The Kombo ID of the application this attachment belongs to, when the ATS files it under one specific application. Many systems attach files to the candidate instead, in which case this is `null`."""

    type: Nullable[GetAtsAttachmentsPositiveResponseType]
    r"""What the file is used for in the ATS. Anything that is neither a CV nor a cover letter is reported as `OTHER`."""

    file_name: Nullable[str]
    r"""The name of the file as reported by the ATS."""

    remote_created_at: Nullable[datetime]
    r"""The date and time the object was created in the remote system.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """

    remote_updated_at: Nullable[datetime]
    r"""A timestamp retrieved from the remote system, describing when the resource was last updated.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """

    changed_at: datetime
    r"""The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """

    remote_deleted_at: Nullable[datetime]
    r"""The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """

    content_ref: OptionalNullable[ContentRef] = UNSET
    r"""Where we stored the file in the bucket you configured. The file is written before the attachment shows up here, so this is set on every attachment you can read."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["content_ref"])
        nullable_fields = set(
            [
                "application_id",
                "type",
                "file_name",
                "content_ref",
                "remote_created_at",
                "remote_updated_at",
                "remote_deleted_at",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetAtsAttachmentsPositiveResponseDataTypedDict(TypedDict):
    next: Nullable[str]
    r"""Cursor string that can be passed to the `cursor` query parameter to get the next page. If this is `null`, then there are no more pages."""
    results: List[GetAtsAttachmentsPositiveResponseResultTypedDict]


class GetAtsAttachmentsPositiveResponseData(BaseModel):
    next: Nullable[str]
    r"""Cursor string that can be passed to the `cursor` query parameter to get the next page. If this is `null`, then there are no more pages."""

    results: List[GetAtsAttachmentsPositiveResponseResult]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetAtsAttachmentsPositiveResponseTypedDict(TypedDict):
    data: GetAtsAttachmentsPositiveResponseDataTypedDict
    status: Literal["success"]


class GetAtsAttachmentsPositiveResponse(BaseModel):
    data: GetAtsAttachmentsPositiveResponseData

    STATUS: Annotated[
        Annotated[Literal["success"], AfterValidator(validate_const("success"))],
        pydantic.Field(alias="status"),
    ] = "success"


try:
    ContentRef.model_rebuild()
except NameError:
    pass
try:
    GetAtsAttachmentsPositiveResponse.model_rebuild()
except NameError:
    pass
