"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date, datetime
from kombo.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from kombo.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Any, Dict, List, Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class GetHrisPayslipsPositiveResponseGrossPayTypedDict(TypedDict):
    r"""The total gross pay for the payslip, before taxes and after gross deductions."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""
    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class GetHrisPayslipsPositiveResponseGrossPay(BaseModel):
    r"""The total gross pay for the payslip, before taxes and after gross deductions."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""

    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class GetHrisPayslipsPositiveResponseNetPayTypedDict(TypedDict):
    r"""The total net pay for the payslip, after taxes have been applied to the gross pay."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""
    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class GetHrisPayslipsPositiveResponseNetPay(BaseModel):
    r"""The total net pay for the payslip, after taxes have been applied to the gross pay."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""

    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class GetHrisPayslipsPositiveResponsePaidAmountTypedDict(TypedDict):
    r"""The amount of the payslip that was actually paid out to the employee. This value accounts for net earnings and deductions."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""
    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class GetHrisPayslipsPositiveResponsePaidAmount(BaseModel):
    r"""The amount of the payslip that was actually paid out to the employee. This value accounts for net earnings and deductions."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""

    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class GrossPayYtdTypedDict(TypedDict):
    r"""The year-to-date gross pay as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""
    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class GrossPayYtd(BaseModel):
    r"""The year-to-date gross pay as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""

    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class NetPayYtdTypedDict(TypedDict):
    r"""The year-to-date net pay as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""
    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class NetPayYtd(BaseModel):
    r"""The year-to-date net pay as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""

    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class PaidAmountYtdTypedDict(TypedDict):
    r"""The year-to-date paid amount as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""
    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class PaidAmountYtd(BaseModel):
    r"""The year-to-date paid amount as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""

    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class GetHrisPayslipsPositiveResponseTotalsTypedDict(TypedDict):
    gross_pay: NotRequired[Nullable[GetHrisPayslipsPositiveResponseGrossPayTypedDict]]
    r"""The total gross pay for the payslip, before taxes and after gross deductions."""
    net_pay: NotRequired[Nullable[GetHrisPayslipsPositiveResponseNetPayTypedDict]]
    r"""The total net pay for the payslip, after taxes have been applied to the gross pay."""
    paid_amount: NotRequired[
        Nullable[GetHrisPayslipsPositiveResponsePaidAmountTypedDict]
    ]
    r"""The amount of the payslip that was actually paid out to the employee. This value accounts for net earnings and deductions."""
    gross_pay_ytd: NotRequired[Nullable[GrossPayYtdTypedDict]]
    r"""The year-to-date gross pay as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""
    net_pay_ytd: NotRequired[Nullable[NetPayYtdTypedDict]]
    r"""The year-to-date net pay as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""
    paid_amount_ytd: NotRequired[Nullable[PaidAmountYtdTypedDict]]
    r"""The year-to-date paid amount as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""


class GetHrisPayslipsPositiveResponseTotals(BaseModel):
    gross_pay: OptionalNullable[GetHrisPayslipsPositiveResponseGrossPay] = UNSET
    r"""The total gross pay for the payslip, before taxes and after gross deductions."""

    net_pay: OptionalNullable[GetHrisPayslipsPositiveResponseNetPay] = UNSET
    r"""The total net pay for the payslip, after taxes have been applied to the gross pay."""

    paid_amount: OptionalNullable[GetHrisPayslipsPositiveResponsePaidAmount] = UNSET
    r"""The amount of the payslip that was actually paid out to the employee. This value accounts for net earnings and deductions."""

    gross_pay_ytd: OptionalNullable[GrossPayYtd] = UNSET
    r"""The year-to-date gross pay as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""

    net_pay_ytd: OptionalNullable[NetPayYtd] = UNSET
    r"""The year-to-date net pay as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""

    paid_amount_ytd: OptionalNullable[PaidAmountYtd] = UNSET
    r"""The year-to-date paid amount as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "gross_pay",
                "net_pay",
                "paid_amount",
                "gross_pay_ytd",
                "net_pay_ytd",
                "paid_amount_ytd",
            ]
        )
        nullable_fields = set(
            [
                "gross_pay",
                "net_pay",
                "paid_amount",
                "gross_pay_ytd",
                "net_pay_ytd",
                "paid_amount_ytd",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class EmployeeTypedDict(TypedDict):
    r"""The employee that the payslip is for."""

    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""
    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""
    first_name: Nullable[str]
    r"""The employee’s first name."""
    last_name: Nullable[str]
    r"""The employee’s last name."""
    display_full_name: Nullable[str]
    r"""The employee’s full name, including any middle names. Not all HR systems provide an explicit display name, so we recommend falling back to `first_name` and `last_name`."""
    remote_deleted_at: Nullable[datetime]
    r"""The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    work_email: NotRequired[Nullable[str]]
    r"""The employee’s work email address. If the email address is invalid, we will set this to `null`."""


class Employee(BaseModel):
    r"""The employee that the payslip is for."""

    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""

    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""

    first_name: Nullable[str]
    r"""The employee’s first name."""

    last_name: Nullable[str]
    r"""The employee’s last name."""

    display_full_name: Nullable[str]
    r"""The employee’s full name, including any middle names. Not all HR systems provide an explicit display name, so we recommend falling back to `first_name` and `last_name`."""

    remote_deleted_at: Nullable[datetime]
    r"""The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """

    work_email: OptionalNullable[str] = UNSET
    r"""The employee’s work email address. If the email address is invalid, we will set this to `null`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["work_email"])
        nullable_fields = set(
            [
                "first_name",
                "last_name",
                "display_full_name",
                "work_email",
                "remote_deleted_at",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class PayRunTypedDict(TypedDict):
    r"""The pay run the payslip was paid out through."""

    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""
    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""
    start_date: Nullable[date]
    r"""The start date of the pay run, as a calendar date (`yyyy-MM-dd`)."""
    end_date: Nullable[date]
    r"""The end date of the pay run, as a calendar date (`yyyy-MM-dd`)."""
    legal_entity_id: Nullable[str]
    r"""The Kombo ID of the pay run’s legal entity. The ID can be used to retrieve the legal entity from the `get legal entities` endpoint."""


class PayRun(BaseModel):
    r"""The pay run the payslip was paid out through."""

    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""

    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""

    start_date: Nullable[date]
    r"""The start date of the pay run, as a calendar date (`yyyy-MM-dd`)."""

    end_date: Nullable[date]
    r"""The end date of the pay run, as a calendar date (`yyyy-MM-dd`)."""

    legal_entity_id: Nullable[str]
    r"""The Kombo ID of the pay run’s legal entity. The ID can be used to retrieve the legal entity from the `get legal entities` endpoint."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class PayCodeTypedDict(TypedDict):
    r"""The pay code (salary type) this line item belongs to in the remote system."""

    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""
    remote_label: Nullable[str]
    r"""The name of the salary type as it appears in the remote system."""


class PayCode(BaseModel):
    r"""The pay code (salary type) this line item belongs to in the remote system."""

    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""

    remote_label: Nullable[str]
    r"""The name of the salary type as it appears in the remote system."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class AmountTypedDict(TypedDict):
    r"""The amount of the line item."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""
    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class Amount(BaseModel):
    r"""The amount of the line item."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""

    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class AmountYtdTypedDict(TypedDict):
    r"""The year-to-date amount of the line item as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""
    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class AmountYtd(BaseModel):
    r"""The year-to-date amount of the line item as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""

    value: float
    r"""The monetary value. See the integration’s limitations for whether this value is rounded. Rounded values use mathematical rounding (half away from zero)."""


class LineItemTypedDict(TypedDict):
    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing. For some integrations, this ID can still change if the payslip is edited."""
    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key. This value may include the item's position on the payslip, which can change if the payslip is edited."""
    name: Nullable[str]
    r"""The name of the salary type."""
    pay_code: PayCodeTypedDict
    r"""The pay code (salary type) this line item belongs to in the remote system."""
    custom_fields: Nullable[Dict[str, Any]]
    r"""A key-value store of fields not covered by the schema. [Read more](/custom-fields)"""
    amount: NotRequired[Nullable[AmountTypedDict]]
    r"""The amount of the line item."""
    amount_ytd: NotRequired[Nullable[AmountYtdTypedDict]]
    r"""The year-to-date amount of the line item as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""


class LineItem(BaseModel):
    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing. For some integrations, this ID can still change if the payslip is edited."""

    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key. This value may include the item's position on the payslip, which can change if the payslip is edited."""

    name: Nullable[str]
    r"""The name of the salary type."""

    pay_code: PayCode
    r"""The pay code (salary type) this line item belongs to in the remote system."""

    custom_fields: Nullable[Dict[str, Any]]
    r"""A key-value store of fields not covered by the schema. [Read more](/custom-fields)"""

    amount: OptionalNullable[Amount] = UNSET
    r"""The amount of the line item."""

    amount_ytd: OptionalNullable[AmountYtd] = UNSET
    r"""The year-to-date amount of the line item as returned by the remote system. Kombo never calculates this value. `null` when the remote API does not provide a year-to-date amount."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["amount", "amount_ytd"])
        nullable_fields = set(["name", "amount", "amount_ytd", "custom_fields"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetHrisPayslipsPositiveResponseResultTypedDict(TypedDict):
    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""
    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""
    custom_fields: Nullable[Dict[str, Any]]
    r"""A key-value store of fields not covered by the schema. [Read more](/custom-fields)"""
    changed_at: datetime
    r"""The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    remote_deleted_at: Nullable[datetime]
    r"""The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    totals: GetHrisPayslipsPositiveResponseTotalsTypedDict
    employee: EmployeeTypedDict
    r"""The employee that the payslip is for."""
    pay_run: Nullable[PayRunTypedDict]
    r"""The pay run the payslip was paid out through."""
    line_items: List[LineItemTypedDict]
    r"""The individual earnings, deductions, and contributions that make up the payslip."""


class GetHrisPayslipsPositiveResponseResult(BaseModel):
    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""

    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""

    custom_fields: Nullable[Dict[str, Any]]
    r"""A key-value store of fields not covered by the schema. [Read more](/custom-fields)"""

    changed_at: datetime
    r"""The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """

    remote_deleted_at: Nullable[datetime]
    r"""The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """

    totals: GetHrisPayslipsPositiveResponseTotals

    employee: Employee
    r"""The employee that the payslip is for."""

    pay_run: Nullable[PayRun]
    r"""The pay run the payslip was paid out through."""

    line_items: List[LineItem]
    r"""The individual earnings, deductions, and contributions that make up the payslip."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetHrisPayslipsPositiveResponseDataTypedDict(TypedDict):
    next: Nullable[str]
    r"""Cursor string that can be passed to the `cursor` query parameter to get the next page. If this is `null`, then there are no more pages."""
    results: List[GetHrisPayslipsPositiveResponseResultTypedDict]


class GetHrisPayslipsPositiveResponseData(BaseModel):
    next: Nullable[str]
    r"""Cursor string that can be passed to the `cursor` query parameter to get the next page. If this is `null`, then there are no more pages."""

    results: List[GetHrisPayslipsPositiveResponseResult]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetHrisPayslipsPositiveResponseTypedDict(TypedDict):
    data: GetHrisPayslipsPositiveResponseDataTypedDict
    status: Literal["success"]


class GetHrisPayslipsPositiveResponse(BaseModel):
    data: GetHrisPayslipsPositiveResponseData

    STATUS: Annotated[
        Annotated[Literal["success"], AfterValidator(validate_const("success"))],
        pydantic.Field(alias="status"),
    ] = "success"


try:
    GetHrisPayslipsPositiveResponse.model_rebuild()
except NameError:
    pass
