"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date, datetime
from kombo.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from kombo.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class GetHrisPayRunsPositiveResponseGrossPayTypedDict(TypedDict):
    r"""The total gross pay for the pay run, before taxes and after gross deductions."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""
    value: float
    r"""The monetary value."""


class GetHrisPayRunsPositiveResponseGrossPay(BaseModel):
    r"""The total gross pay for the pay run, before taxes and after gross deductions."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""

    value: float
    r"""The monetary value."""


class GetHrisPayRunsPositiveResponseNetPayTypedDict(TypedDict):
    r"""The total net pay for the pay run, after taxes have been applied to the gross pay."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""
    value: float
    r"""The monetary value."""


class GetHrisPayRunsPositiveResponseNetPay(BaseModel):
    r"""The total net pay for the pay run, after taxes have been applied to the gross pay."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""

    value: float
    r"""The monetary value."""


class GetHrisPayRunsPositiveResponsePaidAmountTypedDict(TypedDict):
    r"""The total amount paid out through the pay run. This value accounts for net earnings and deductions."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""
    value: float
    r"""The monetary value."""


class GetHrisPayRunsPositiveResponsePaidAmount(BaseModel):
    r"""The total amount paid out through the pay run. This value accounts for net earnings and deductions."""

    currency: str
    r"""The [ISO 4217 currency code](https://www.iso.org/iso-4217-currency-codes.html) the value is denominated in."""

    value: float
    r"""The monetary value."""


class GetHrisPayRunsPositiveResponseTotalsTypedDict(TypedDict):
    gross_pay: NotRequired[Nullable[GetHrisPayRunsPositiveResponseGrossPayTypedDict]]
    r"""The total gross pay for the pay run, before taxes and after gross deductions."""
    net_pay: NotRequired[Nullable[GetHrisPayRunsPositiveResponseNetPayTypedDict]]
    r"""The total net pay for the pay run, after taxes have been applied to the gross pay."""
    paid_amount: NotRequired[
        Nullable[GetHrisPayRunsPositiveResponsePaidAmountTypedDict]
    ]
    r"""The total amount paid out through the pay run. This value accounts for net earnings and deductions."""


class GetHrisPayRunsPositiveResponseTotals(BaseModel):
    gross_pay: OptionalNullable[GetHrisPayRunsPositiveResponseGrossPay] = UNSET
    r"""The total gross pay for the pay run, before taxes and after gross deductions."""

    net_pay: OptionalNullable[GetHrisPayRunsPositiveResponseNetPay] = UNSET
    r"""The total net pay for the pay run, after taxes have been applied to the gross pay."""

    paid_amount: OptionalNullable[GetHrisPayRunsPositiveResponsePaidAmount] = UNSET
    r"""The total amount paid out through the pay run. This value accounts for net earnings and deductions."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["gross_pay", "net_pay", "paid_amount"])
        nullable_fields = set(["gross_pay", "net_pay", "paid_amount"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetHrisPayRunsPositiveResponseResultTypedDict(TypedDict):
    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""
    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""
    start_date: Nullable[date]
    r"""The start date of the pay run, as a calendar date (`yyyy-MM-dd`)."""
    end_date: Nullable[date]
    r"""The end date of the pay run, as a calendar date (`yyyy-MM-dd`)."""
    legal_entity_id: Nullable[str]
    r"""The Kombo ID of the pay run’s legal entity. The ID can be used to retrieve the legal entity from the `get legal entities` endpoint."""
    changed_at: datetime
    r"""The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    remote_deleted_at: Nullable[datetime]
    r"""The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """
    totals: GetHrisPayRunsPositiveResponseTotalsTypedDict


class GetHrisPayRunsPositiveResponseResult(BaseModel):
    id: str
    r"""The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing."""

    remote_id: str
    r"""The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key."""

    start_date: Nullable[date]
    r"""The start date of the pay run, as a calendar date (`yyyy-MM-dd`)."""

    end_date: Nullable[date]
    r"""The end date of the pay run, as a calendar date (`yyyy-MM-dd`)."""

    legal_entity_id: Nullable[str]
    r"""The Kombo ID of the pay run’s legal entity. The ID can be used to retrieve the legal entity from the `get legal entities` endpoint."""

    changed_at: datetime
    r"""The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """

    remote_deleted_at: Nullable[datetime]
    r"""The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
    """

    totals: GetHrisPayRunsPositiveResponseTotals

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetHrisPayRunsPositiveResponseDataTypedDict(TypedDict):
    next: Nullable[str]
    r"""Cursor string that can be passed to the `cursor` query parameter to get the next page. If this is `null`, then there are no more pages."""
    results: List[GetHrisPayRunsPositiveResponseResultTypedDict]


class GetHrisPayRunsPositiveResponseData(BaseModel):
    next: Nullable[str]
    r"""Cursor string that can be passed to the `cursor` query parameter to get the next page. If this is `null`, then there are no more pages."""

    results: List[GetHrisPayRunsPositiveResponseResult]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetHrisPayRunsPositiveResponseTypedDict(TypedDict):
    data: GetHrisPayRunsPositiveResponseDataTypedDict
    status: Literal["success"]


class GetHrisPayRunsPositiveResponse(BaseModel):
    data: GetHrisPayRunsPositiveResponseData

    STATUS: Annotated[
        Annotated[Literal["success"], AfterValidator(validate_const("success"))],
        pydantic.Field(alias="status"),
    ] = "success"


try:
    GetHrisPayRunsPositiveResponse.model_rebuild()
except NameError:
    pass
