"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from kombo.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal
from typing_extensions import TypedDict


IssueStatusChangedWebhookPayloadType = Literal["issue-status-changed",]
r"""Type of the webhook event"""


Change = Literal[
    "raised",
    "resolved",
]
r"""Why this webhook was sent: the issue was raised or resolved."""


IssueStatusChangedWebhookPayloadStatus = Literal[
    "OPEN",
    "RESOLVED",
]
r"""The issue status after this change."""


class IssueTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the issue."""
    type: str
    r"""The issue type, for example `integration.authentication_failed`. Kombo will add more types over time. Treat unknown values as valid and handle them without failing."""
    title: str
    r"""A short, customer-facing title for this issue type."""
    status: IssueStatusChangedWebhookPayloadStatus
    r"""The issue status after this change."""
    markdown_message: str
    r"""What is wrong and how to investigate or fix it."""
    first_observed_at: datetime
    r"""ISO 8601 timestamp when Kombo first observed this episode of the issue."""
    resolved_at: Nullable[datetime]
    r"""ISO 8601 timestamp when the issue was resolved. `null` while it is open."""


class Issue(BaseModel):
    id: str
    r"""The unique identifier of the issue."""

    type: str
    r"""The issue type, for example `integration.authentication_failed`. Kombo will add more types over time. Treat unknown values as valid and handle them without failing."""

    title: str
    r"""A short, customer-facing title for this issue type."""

    status: IssueStatusChangedWebhookPayloadStatus
    r"""The issue status after this change."""

    markdown_message: str
    r"""What is wrong and how to investigate or fix it."""

    first_observed_at: datetime
    r"""ISO 8601 timestamp when Kombo first observed this episode of the issue."""

    resolved_at: Nullable[datetime]
    r"""ISO 8601 timestamp when the issue was resolved. `null` while it is open."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


IssueStatusChangedWebhookPayloadCategory = Literal[
    "HRIS",
    "ATS",
    "ASSESSMENT",
    "LMS",
]
r"""The category of the integration (HRIS, ATS, ASSESSMENT, or LMS)."""


class IssueStatusChangedWebhookPayloadEndUserTypedDict(TypedDict):
    r"""Information about the end user who created the integration."""

    organization_name: str
    r"""The name of the organization that owns the integration."""
    creator_email: Nullable[str]
    r"""The email address of the user who created the integration."""
    origin_id: Nullable[str]
    r"""The unique identifier of the organization in the integrated system."""


class IssueStatusChangedWebhookPayloadEndUser(BaseModel):
    r"""Information about the end user who created the integration."""

    organization_name: str
    r"""The name of the organization that owns the integration."""

    creator_email: Nullable[str]
    r"""The email address of the user who created the integration."""

    origin_id: Nullable[str]
    r"""The unique identifier of the organization in the integrated system."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class IntegrationTypedDict(TypedDict):
    r"""The integration this issue belongs to. `null` for environment-wide issues."""

    id: str
    r"""The unique identifier of the integration."""
    tool: str
    r"""The name of the integrated tool (e.g., \"personio\", \"greenhouse\")."""
    category: IssueStatusChangedWebhookPayloadCategory
    r"""The category of the integration (HRIS, ATS, ASSESSMENT, or LMS)."""
    end_user: IssueStatusChangedWebhookPayloadEndUserTypedDict
    r"""Information about the end user who created the integration."""


class Integration(BaseModel):
    r"""The integration this issue belongs to. `null` for environment-wide issues."""

    id: str
    r"""The unique identifier of the integration."""

    tool: str
    r"""The name of the integrated tool (e.g., \"personio\", \"greenhouse\")."""

    category: IssueStatusChangedWebhookPayloadCategory
    r"""The category of the integration (HRIS, ATS, ASSESSMENT, or LMS)."""

    end_user: IssueStatusChangedWebhookPayloadEndUser
    r"""Information about the end user who created the integration."""


class IssueStatusChangedWebhookPayloadDataTypedDict(TypedDict):
    change: Change
    r"""Why this webhook was sent: the issue was raised or resolved."""
    issue: IssueTypedDict
    integration: Nullable[IntegrationTypedDict]
    r"""The integration this issue belongs to. `null` for environment-wide issues."""


class IssueStatusChangedWebhookPayloadData(BaseModel):
    change: Change
    r"""Why this webhook was sent: the issue was raised or resolved."""

    issue: Issue

    integration: Nullable[Integration]
    r"""The integration this issue belongs to. `null` for environment-wide issues."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class IssueStatusChangedWebhookPayloadTypedDict(TypedDict):
    id: str
    r"""Unique identifier for this webhook event"""
    type: IssueStatusChangedWebhookPayloadType
    r"""Type of the webhook event"""
    data: IssueStatusChangedWebhookPayloadDataTypedDict


class IssueStatusChangedWebhookPayload(BaseModel):
    id: str
    r"""Unique identifier for this webhook event"""

    type: IssueStatusChangedWebhookPayloadType
    r"""Type of the webhook event"""

    data: IssueStatusChangedWebhookPayloadData
