"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kombo.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal
from typing_extensions import TypedDict


KomboHrisErrorStatus = Literal["error",]


KomboHrisErrorCode = Literal[
    "PLATFORM.RATE_LIMIT_EXCEEDED",
    "PLATFORM.INTEGRATION_NOT_FOUND",
    "PLATFORM.INPUT_INVALID",
    "PLATFORM.UNKNOWN_ERROR",
    "PLATFORM.IP_NOT_WHITELISTED",
    "PLATFORM.AUTHENTICATION_INVALID",
    "PLATFORM.TASK_TIMED_OUT",
    "INTEGRATION.PERMISSION_MISSING",
    "INTEGRATION.AUTHENTICATION_INVALID",
    "INTEGRATION.QA_FAILED",
    "INTEGRATION.SETUP_SYNC_PENDING",
    "INTEGRATION.SETUP_INCOMPLETE",
    "INTEGRATION.INACTIVE",
    "INTEGRATION.MODEL_NOT_AVAILABLE",
    "INTEGRATION.MODEL_DISABLED",
    "INTEGRATION.ACTION_NOT_AVAILABLE",
    "INTEGRATION.ACTION_DISABLED",
    "REMOTE.SERVICE_UNAVAILABLE",
    "REMOTE.RATE_LIMIT_EXCEEDED",
    "REMOTE.INPUT_INVALID",
    "REMOTE.UNKNOWN_HTTP_ERROR",
    "HRIS.EMPLOYEE_ALREADY_EXISTS",
]
r"""Some errors include an error code that can be used to identify their cause. See the [Error Handling Docs](https://docs.kombo.dev/guides/errors) for more information. For your error handling logic please use the error `code` instead of other properties (e.g. message, http status code, ...)."""


class KomboHrisErrorErrorTypedDict(TypedDict):
    r"""Error details with structured code for programmatic handling."""

    code: Nullable[KomboHrisErrorCode]
    r"""Some errors include an error code that can be used to identify their cause. See the [Error Handling Docs](https://docs.kombo.dev/guides/errors) for more information. For your error handling logic please use the error `code` instead of other properties (e.g. message, http status code, ...)."""
    title: Nullable[str]
    r"""A static, human-readable label."""
    message: str
    r"""A dynamic, detailed description of what went wrong in this specific instance."""
    log_url: Nullable[str]
    r"""The log page in the Kombo UI lists every interaction with full details. If you need assistance, share that link with our support team."""


class KomboHrisErrorError(BaseModel):
    r"""Error details with structured code for programmatic handling."""

    code: Nullable[KomboHrisErrorCode]
    r"""Some errors include an error code that can be used to identify their cause. See the [Error Handling Docs](https://docs.kombo.dev/guides/errors) for more information. For your error handling logic please use the error `code` instead of other properties (e.g. message, http status code, ...)."""

    title: Nullable[str]
    r"""A static, human-readable label."""

    message: str
    r"""A dynamic, detailed description of what went wrong in this specific instance."""

    log_url: Nullable[str]
    r"""The log page in the Kombo UI lists every interaction with full details. If you need assistance, share that link with our support team."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
