"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kombo.types import BaseModel, UNSET_SENTINEL
from kombo.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostConnectCreateLinkPositiveResponseDataTypedDict(TypedDict):
    link: str
    static_ips: NotRequired[List[str]]
    r"""The allowlist IPs for this integration. Present when `enable_static_ips` is `true`."""


class PostConnectCreateLinkPositiveResponseData(BaseModel):
    link: str

    static_ips: Optional[List[str]] = None
    r"""The allowlist IPs for this integration. Present when `enable_static_ips` is `true`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["static_ips"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PostConnectCreateLinkPositiveResponseTypedDict(TypedDict):
    data: PostConnectCreateLinkPositiveResponseDataTypedDict
    status: Literal["success"]


class PostConnectCreateLinkPositiveResponse(BaseModel):
    data: PostConnectCreateLinkPositiveResponseData

    STATUS: Annotated[
        Annotated[Literal["success"], AfterValidator(validate_const("success"))],
        pydantic.Field(alias="status"),
    ] = "success"


try:
    PostConnectCreateLinkPositiveResponse.model_rebuild()
except NameError:
    pass
