"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .posthrisemployeesemployeeiddocumentsrequestbody import (
    PostHrisEmployeesEmployeeIDDocumentsRequestBody,
    PostHrisEmployeesEmployeeIDDocumentsRequestBodyTypedDict,
)
from kombo.types import BaseModel, UNSET_SENTINEL
from kombo.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostHrisEmployeesEmployeeIDDocumentsGlobalsTypedDict(TypedDict):
    integration_id: NotRequired[str]
    r"""ID of the integration you want to interact with."""


class PostHrisEmployeesEmployeeIDDocumentsGlobals(BaseModel):
    integration_id: Annotated[
        Optional[str],
        pydantic.Field(alias="X-Integration-Id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""ID of the integration you want to interact with."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["integration_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PostHrisEmployeesEmployeeIDDocumentsRequestTypedDict(TypedDict):
    employee_id: str
    r"""POST /hris/employees/:employee_id/documents Parameter"""
    body: PostHrisEmployeesEmployeeIDDocumentsRequestBodyTypedDict
    r"""POST /hris/employees/:employee_id/documents Request body"""


class PostHrisEmployeesEmployeeIDDocumentsRequest(BaseModel):
    employee_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""POST /hris/employees/:employee_id/documents Parameter"""

    body: Annotated[
        PostHrisEmployeesEmployeeIDDocumentsRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""POST /hris/employees/:employee_id/documents Request body"""
