"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kombo.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


PostForceSyncRequestBodyType = Literal[
    "FULL",
    "DELTA",
]
r"""The type of the triggered sync."""


class PostForceSyncRequestBodyTypedDict(TypedDict):
    type: NotRequired[PostForceSyncRequestBodyType]
    r"""The type of the triggered sync."""


class PostForceSyncRequestBody(BaseModel):
    type: Optional[PostForceSyncRequestBodyType] = "FULL"
    r"""The type of the triggered sync."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
