"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kombo.types import BaseModel, Nullable, OptionalNullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal
from typing_extensions import NotRequired, TypedDict


PostIntegrationsIntegrationIDSetupLinkRequestBodyLanguage = Literal[
    "en",
    "de",
    "fr",
    "it",
    "es",
]
r"""Language of the setup flow UI."""


PostIntegrationsIntegrationIDSetupLinkRequestBodyLinkType = Literal[
    "EMBEDDED",
    "MAGIC_LINK",
]
r"""The type of link you want to create. `EMBEDDED` is for the [embedded flow](../guides/connect/embedded-flow) using the Kombo Connect SDK (these links are valid for 1 hour) and `MAGIC_LINK` is for [magic links](../guides/connect/magic-links) which you send out manually to customers (these are valid for 1 year)."""


class PostIntegrationsIntegrationIDSetupLinkRequestBodyTypedDict(TypedDict):
    link_type: PostIntegrationsIntegrationIDSetupLinkRequestBodyLinkType
    r"""The type of link you want to create. `EMBEDDED` is for the [embedded flow](../guides/connect/embedded-flow) using the Kombo Connect SDK (these links are valid for 1 hour) and `MAGIC_LINK` is for [magic links](../guides/connect/magic-links) which you send out manually to customers (these are valid for 1 year)."""
    language: NotRequired[
        Nullable[PostIntegrationsIntegrationIDSetupLinkRequestBodyLanguage]
    ]
    r"""Language of the setup flow UI."""


class PostIntegrationsIntegrationIDSetupLinkRequestBody(BaseModel):
    link_type: PostIntegrationsIntegrationIDSetupLinkRequestBodyLinkType
    r"""The type of link you want to create. `EMBEDDED` is for the [embedded flow](../guides/connect/embedded-flow) using the Kombo Connect SDK (these links are valid for 1 hour) and `MAGIC_LINK` is for [magic links](../guides/connect/magic-links) which you send out manually to customers (these are valid for 1 year)."""

    language: OptionalNullable[
        PostIntegrationsIntegrationIDSetupLinkRequestBodyLanguage
    ] = "en"
    r"""Language of the setup flow UI."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["language"])
        nullable_fields = set(["language"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
