"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kombo.types import BaseModel
from kombo.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class PostIntegrationsIntegrationIDSetupLinkPositiveResponseDataTypedDict(TypedDict):
    link: str
    r"""The setup link URL to pass to the Kombo Connect SDK."""


class PostIntegrationsIntegrationIDSetupLinkPositiveResponseData(BaseModel):
    link: str
    r"""The setup link URL to pass to the Kombo Connect SDK."""


class PostIntegrationsIntegrationIDSetupLinkPositiveResponseTypedDict(TypedDict):
    data: PostIntegrationsIntegrationIDSetupLinkPositiveResponseDataTypedDict
    status: Literal["success"]


class PostIntegrationsIntegrationIDSetupLinkPositiveResponse(BaseModel):
    data: PostIntegrationsIntegrationIDSetupLinkPositiveResponseData

    STATUS: Annotated[
        Annotated[Literal["success"], AfterValidator(validate_const("success"))],
        pydantic.Field(alias="status"),
    ] = "success"


try:
    PostIntegrationsIntegrationIDSetupLinkPositiveResponse.model_rebuild()
except NameError:
    pass
