"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .postintegrationsintegrationidsetuplinkrequestbody import (
    PostIntegrationsIntegrationIDSetupLinkRequestBody,
    PostIntegrationsIntegrationIDSetupLinkRequestBodyTypedDict,
)
from kombo.types import BaseModel
from kombo.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class PostIntegrationsIntegrationIDSetupLinkRequestTypedDict(TypedDict):
    integration_id: str
    r"""POST /integrations/:integration_id/setup-link Parameter"""
    body: PostIntegrationsIntegrationIDSetupLinkRequestBodyTypedDict
    r"""POST /integrations/:integration_id/setup-link Request body"""


class PostIntegrationsIntegrationIDSetupLinkRequest(BaseModel):
    integration_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""POST /integrations/:integration_id/setup-link Parameter"""

    body: Annotated[
        PostIntegrationsIntegrationIDSetupLinkRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""POST /integrations/:integration_id/setup-link Request body"""
