"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kombo.types import BaseModel
from kombo.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class PutIntegrationsIntegrationIDEnabledPositiveResponseDataTypedDict(TypedDict):
    pass


class PutIntegrationsIntegrationIDEnabledPositiveResponseData(BaseModel):
    pass


class PutIntegrationsIntegrationIDEnabledPositiveResponseTypedDict(TypedDict):
    data: PutIntegrationsIntegrationIDEnabledPositiveResponseDataTypedDict
    status: Literal["success"]


class PutIntegrationsIntegrationIDEnabledPositiveResponse(BaseModel):
    data: PutIntegrationsIntegrationIDEnabledPositiveResponseData

    STATUS: Annotated[
        Annotated[Literal["success"], AfterValidator(validate_const("success"))],
        pydantic.Field(alias="status"),
    ] = "success"


try:
    PutIntegrationsIntegrationIDEnabledPositiveResponse.model_rebuild()
except NameError:
    pass
