workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    kombo-prepared-spec:
        inputs:
            - location: https://api.kombo.dev/internal/sdk.openapi.yaml
              authHeader: Authorization
              authSecret: $openapi_doc_auth_token
        registry:
            location: registry.speakeasyapi.dev/kombo-ayg/api/kombo-api
targets:
    kombo-python:
        target: python
        source: kombo-prepared-spec
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/kombo-ayg/api/kombo-api-python-code-samples
            blocking: false
        testing:
            enabled: false
