"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "kombo"
__version__: str = "1.3.3"
__openapi_doc_version__: str = "1.0.0"
__gen_version__: str = "2.918.3"
__user_agent__: str = "speakeasy-sdk/python 1.3.3 2.918.3 1.0.0 kombo"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
